CheatSheet for using tensorflow eager execution : Ada beberapa benefit lho 

- Execution Line by line
- Support Vektorisasi
- Operator Overloading < jadi gausah ribet kalau mau nambahin / lakuin operasi aritmatika tensor obj > 
- Kompatibel dengan numpy < Ntar ada contoh nya > intinya tf obj bisa diproses menggunakan numpy function


In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.1.0


In [2]:
# Support vektorisasi Example
matrix = tf.constant([1,2,3,4,5,6],shape=(2,3))
matrix = tf.add(matrix,2)
print(matrix)

tf.Tensor(
[[3 4 5]
 [6 7 8]], shape=(2, 3), dtype=int32)


In [3]:
# Operator Overloading 
matrix = matrix * 2
print(matrix)

tf.Tensor(
[[ 6  8 10]
 [12 14 16]], shape=(2, 3), dtype=int32)


In [4]:
#Contoh numpy compatibility
x = tf.constant([1,2,3,4,8,6],dtype=tf.float32)
y = tf.constant([2,3,4,5,6,7],dtype=tf.float32)

print(np.multiply(x,y))
print(np.reshape(x,(2,3)))
print(np.where(x%2 == 0,1,"Ngab"))
print(np.argmax(x,axis=None))

[ 2.  6. 12. 20. 48. 42.]
[[1. 2. 3.]
 [4. 8. 6.]]
['Ngab' '1' 'Ngab' '1' '1' '1']
4


In [5]:
# Numpy interopability < BIsa juga dari numpy ke Tensor Obj > LOL
arr = np.array([1,2,3,4])
print( tf.cast(arr,tf.float32) )
print(tf.multiply(arr,4))
print(tf.where(arr % 2 ==0, "ngab", "Lhoo"))
print(tf.eye(3,3))


tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor([ 4  8 12 16], shape=(4,), dtype=int32)
tf.Tensor([b'Lhoo' b'ngab' b'Lhoo' b'ngab'], shape=(4,), dtype=string)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [6]:
v = tf.Variable(0.0,dtype=tf.float32)
v.assign_add(4)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=4.0>

In [7]:
v.read_value().numpy()

4.0

In [8]:
# Training data
x_train = np.array([-1.0, 0.0, ])